quarkus.datasource.db-kind=oracle

quarkus.datasource.username=rm567023
quarkus.datasource.password=SEUACESSO

quarkus.datasource.jdbc.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL

quarkus.http.port=8080

quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.methods=GET,POST,PUT,DELETE
